### PR TITLE
feat: a command to download a blob-type field

### LINKED ISSUE #19: feat: add get-blob command
To create a file which contain the content of a specified property of a specified document as is.

### PR DESCRIPTION
**Pull request by rdrgn**
close #19

### CODE REVIEW

**Comment by rdrgn** [comment]
#15 同様、業務で必要になった際に書いたコードを残しておきます。

**Comment by rdrgn** [comment]
何なら`export`と統合できますね。

**Comment by exKAZUu** [comment]
I think `export` includes a serialization process and `download` doesn't include it. But i agree that there is too similar ... let me think ...

**Comment by rdrgn** [comment]
(I talked with exKAZUu on Discord.)

We'll rename the `download` to `get-blob` and remove the feature to export non-blob fields (and documents) from this command.

**Comment by rdrgn** [comment]
**TODO:** Add an option to provide the output file name.

**Comment by rdrgn** [comment]
Done.

**Review by exKAZUu — APPROVED** [review]
LGTM :+1:

**Review by exKAZUu — APPROVED** [review]
LGTM :+1:

**Pull request merged**
